var namespaceKParts =
[
    [ "BrowserArguments", "structKParts_1_1BrowserArguments.html", "structKParts_1_1BrowserArguments" ],
    [ "BrowserExtension", "classKParts_1_1BrowserExtension.html", "classKParts_1_1BrowserExtension" ],
    [ "BrowserHostExtension", "classKParts_1_1BrowserHostExtension.html", "classKParts_1_1BrowserHostExtension" ],
    [ "BrowserInterface", "classKParts_1_1BrowserInterface.html", "classKParts_1_1BrowserInterface" ],
    [ "BrowserOpenOrSaveQuestion", "classKParts_1_1BrowserOpenOrSaveQuestion.html", "classKParts_1_1BrowserOpenOrSaveQuestion" ],
    [ "BrowserRun", "classKParts_1_1BrowserRun.html", "classKParts_1_1BrowserRun" ],
    [ "Event", "classKParts_1_1Event.html", "classKParts_1_1Event" ],
    [ "Factory", "classKParts_1_1Factory.html", "classKParts_1_1Factory" ],
    [ "FileInfoExtension", "classKParts_1_1FileInfoExtension.html", "classKParts_1_1FileInfoExtension" ],
    [ "GenericFactory", "classKParts_1_1GenericFactory.html", "classKParts_1_1GenericFactory" ],
    [ "GenericFactory< KTypeList< T1, T2 > >", "classKParts_1_1GenericFactory_3_01KTypeList_3_01T1_00_01T2_01_4_01_4.html", "classKParts_1_1GenericFactory_3_01KTypeList_3_01T1_00_01T2_01_4_01_4" ],
    [ "GenericFactoryBase", "classKParts_1_1GenericFactoryBase.html", "classKParts_1_1GenericFactoryBase" ],
    [ "GUIActivateEvent", "classKParts_1_1GUIActivateEvent.html", "classKParts_1_1GUIActivateEvent" ],
    [ "HistoryProvider", "classKParts_1_1HistoryProvider.html", "classKParts_1_1HistoryProvider" ],
    [ "HtmlExtension", "classKParts_1_1HtmlExtension.html", "classKParts_1_1HtmlExtension" ],
    [ "HtmlSettingsInterface", "classKParts_1_1HtmlSettingsInterface.html", "classKParts_1_1HtmlSettingsInterface" ],
    [ "LiveConnectExtension", "classKParts_1_1LiveConnectExtension.html", "classKParts_1_1LiveConnectExtension" ],
    [ "MainWindow", "classKParts_1_1MainWindow.html", "classKParts_1_1MainWindow" ],
    [ "OpenUrlArguments", "classKParts_1_1OpenUrlArguments.html", "classKParts_1_1OpenUrlArguments" ],
    [ "OpenUrlEvent", "classKParts_1_1OpenUrlEvent.html", "classKParts_1_1OpenUrlEvent" ],
    [ "Part", "classKParts_1_1Part.html", "classKParts_1_1Part" ],
    [ "PartActivateEvent", "classKParts_1_1PartActivateEvent.html", "classKParts_1_1PartActivateEvent" ],
    [ "PartBase", "classKParts_1_1PartBase.html", "classKParts_1_1PartBase" ],
    [ "PartManager", "classKParts_1_1PartManager.html", "classKParts_1_1PartManager" ],
    [ "PartSelectEvent", "classKParts_1_1PartSelectEvent.html", "classKParts_1_1PartSelectEvent" ],
    [ "Plugin", "classKParts_1_1Plugin.html", "classKParts_1_1Plugin" ],
    [ "ReadOnlyPart", "classKParts_1_1ReadOnlyPart.html", "classKParts_1_1ReadOnlyPart" ],
    [ "ReadWritePart", "classKParts_1_1ReadWritePart.html", "classKParts_1_1ReadWritePart" ],
    [ "ScriptableExtension", "classKParts_1_1ScriptableExtension.html", "classKParts_1_1ScriptableExtension" ],
    [ "SelectorInterface", "classKParts_1_1SelectorInterface.html", "classKParts_1_1SelectorInterface" ],
    [ "StatusBarExtension", "classKParts_1_1StatusBarExtension.html", "classKParts_1_1StatusBarExtension" ],
    [ "TextExtension", "classKParts_1_1TextExtension.html", "classKParts_1_1TextExtension" ],
    [ "WindowArgs", "classKParts_1_1WindowArgs.html", "classKParts_1_1WindowArgs" ]
];