var namespaceKParts =
[
    [ "BrowserArguments", "structKParts_1_1BrowserArguments.html", null ],
    [ "WindowArgs", "classKParts_1_1WindowArgs.html", null ],
    [ "OpenUrlEvent", "classKParts_1_1OpenUrlEvent.html", null ],
    [ "BrowserExtension", "classKParts_1_1BrowserExtension.html", null ],
    [ "BrowserHostExtension", "classKParts_1_1BrowserHostExtension.html", null ],
    [ "LiveConnectExtension", "classKParts_1_1LiveConnectExtension.html", null ],
    [ "BrowserInterface", "classKParts_1_1BrowserInterface.html", null ],
    [ "BrowserOpenOrSaveQuestion", "classKParts_1_1BrowserOpenOrSaveQuestion.html", null ],
    [ "BrowserRun", "classKParts_1_1BrowserRun.html", null ],
    [ "Event", "classKParts_1_1Event.html", null ],
    [ "GUIActivateEvent", "classKParts_1_1GUIActivateEvent.html", null ],
    [ "PartActivateEvent", "classKParts_1_1PartActivateEvent.html", null ],
    [ "PartSelectEvent", "classKParts_1_1PartSelectEvent.html", null ],
    [ "Factory", "classKParts_1_1Factory.html", null ],
    [ "FileInfoExtension", "classKParts_1_1FileInfoExtension.html", null ],
    [ "GenericFactoryBase", "classKParts_1_1GenericFactoryBase.html", null ],
    [ "GenericFactory", "classKParts_1_1GenericFactory.html", null ],
    [ "GenericFactory< KTypeList< T1, T2 > >", "classKParts_1_1GenericFactory_3_01KTypeList_3_01T1_00_01T2_01_4_01_4.html", null ],
    [ "HistoryProvider", "classKParts_1_1HistoryProvider.html", null ],
    [ "HtmlExtension", "classKParts_1_1HtmlExtension.html", null ],
    [ "SelectorInterface", "classKParts_1_1SelectorInterface.html", null ],
    [ "HtmlSettingsInterface", "classKParts_1_1HtmlSettingsInterface.html", null ],
    [ "MainWindow", "classKParts_1_1MainWindow.html", null ],
    [ "PartBase", "classKParts_1_1PartBase.html", null ],
    [ "Part", "classKParts_1_1Part.html", null ],
    [ "OpenUrlArguments", "classKParts_1_1OpenUrlArguments.html", null ],
    [ "ReadOnlyPart", "classKParts_1_1ReadOnlyPart.html", null ],
    [ "ReadWritePart", "classKParts_1_1ReadWritePart.html", null ],
    [ "PartManager", "classKParts_1_1PartManager.html", null ],
    [ "Plugin", "classKParts_1_1Plugin.html", null ],
    [ "ScriptableExtension", "classKParts_1_1ScriptableExtension.html", null ],
    [ "StatusBarExtension", "classKParts_1_1StatusBarExtension.html", null ],
    [ "TextExtension", "classKParts_1_1TextExtension.html", null ],
    [ "qHash", "namespaceKParts.html#a99af3d8108bfdd82cf3224a3f697e5a6", null ],
    [ "qHash", "namespaceKParts.html#a00b2e80db53d10a549314e5ba7a5a5ef", null ]
];